name: CI - Centralized GitHub Actions Repo Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # dry run

jobs:
  scan:
    uses: ./.github/workflows/scan.yml
    with:
      language: dotnet
    secrets:
      READ_PAT: ${{ secrets.READ_PAT }}
      SLACK_SECURITY_BOT_TOKEN: ${{ secrets.SLACK_SECURITY_BOT_TOKEN }} 

  trivy:
    uses: ./.github/workflows/trivy.yml

  codeql:
    uses: ./.github/workflows/codeql.yml

  notify:
    uses: ./.github/workflows/notify.yml
    with:
      status: "Success"
      message: "CI scan completed successfully"
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  sbom:
    uses: ./.github/workflows/sbom.yml
    with:
      language: dotnet
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  test:
    uses: ./.github/workflows/test.yml
    with:
        language: dotnet 

  lint:
    uses: ./.github/workflows/lint.yml