name: CI - Centralized GitHub Actions Repo Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # dry run

jobs:
  scan:
    uses: ./.github/workflows/scan.yml
    # with:
    #   language: dotnet  # Required if scan.yml uses it

  trivy:
    uses: ./.github/workflows/trivy.yml

  codeql:
    uses: ./.github/workflows/codeql.yml

  notify:
    uses: ./.github/workflows/notify.yml
    with:
      status: "Success"
      message: "CI scan completed successfully"
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  sbom:
    uses: ./.github/workflows/sbom.yml

  test:
    uses: ./.github/workflows/test.yml

  lint:
    uses: ./.github/workflows/lint.yml