name: Reusable Notify

on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string
      message:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK:
        required: true
      GH_TOKEN:
        required: true

permissions:
  contents: read
  pull-requests: write

jobs:
  notify:
    name: Send Notification
    runs-on: ubuntu-latest

    env:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Send Slack Message
        if: env.SLACK_WEBHOOK != ''
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\": \"[${{ inputs.status }}] ${{ inputs.message }}\"}" \
          "$SLACK_WEBHOOK"

      - name: Add GitHub PR Comment
        if: ${{ github.event_name == 'pull_request' && env.GH_TOKEN != '' }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "[${{ inputs.status }}] ${{ inputs.message }}"

  call-audit-log:
    uses: WahbaMousa-DevOps/CENTRALIZED-GITHUB-ACTIONS/.github/workflows/audit.yml@main
    with:
      audit_message: "Notify job completed successfully."
      job_name: "notify"
