name: Reusable SBOM Generation

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install CycloneDX CLI
        run: |
          curl -sSL https://github.com/CycloneDX/cyclonedx-cli/releases/latest/download/cyclonedx-linux-x64 -o cyclonedx
          chmod +x cyclonedx
          sudo mv cyclonedx /usr/local/bin/cyclonedx

      - name: Generate SBOM for ${{ inputs.language }}
        run: |
          case "${{ inputs.language }}" in
            # node)
            #   npm ci
            #   cyclonedx npm -o sbom-node.json
            #   ;;
            # java)
            #   chmod +x ./gradlew
            #   ./gradlew dependencies
            #   cyclonedx java -o sbom-java.json
            #   ;;
            dotnet)
              dotnet restore
              cyclonedx dotnet -o sbom-dotnet.json
              ;;
            *)
              echo "Unsupported language for SBOM"
              exit 1
              ;;
          esac

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image (for SBOM)
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/sbom-${{ inputs.language }}:${{ github.sha }} .

      - name: Generate SBOM from Docker Image (Trivy)
        run: |
          docker run --rm -v "$(pwd):/out" aquasec/trivy image \
            --format cyclonedx --output /out/trivy-sbom-${{ inputs.language }}.json \
            ${{ secrets.DOCKER_USERNAME }}/sbom-${{ inputs.language }}:${{ github.sha }}

  call-audit-log:
    uses: WahbaMousa-DevOps/CENTRALIZED-GITHUB-ACTIONS/.github/workflows/audit.yml@main
    with:
      audit_message: "SBOM job completed successfully."
      job_name: "sbom"
